name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm install
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to. 